### ISSUE TITLE
[Question] <title> Unable to obtain disk information of win system

### ISSUE THREAD

**Issue by lfandrh** [dromara/hertzbeat#1088]
### Question

系统信息：1903版本，内部版本18362.1256。无法获取系统的磁盘信息，尝试获取其他的磁盘信息，发现oid中带有2021的大多都无法访问。![信息图片](https://github.com/lfandrh/figure/blob/master/test/%E6%88%AA%E5%9B%BE.png)

**Comment by lfandrh** [comment]
1.标题中提到的问题解决了，磁盘信息可以在存储信息里面找到。

2.存储信息不仅包括了磁盘信息，还包括了内存信息，使用中遇到的一个问题是内存使用率超过100%，原因是使用了虚拟内存的已使用大小去除以了物理内存的大小，可以将src/main/resources/define/app-windows.yml有关内存的oid修改为：
`hrMemorySize: 1.3.6.1.2.1.25.2.2.0`
 `hrStorageUsed: 1.3.6.1.2.1.25.2.3.1.6.6`
 `hrStorageAllocationUnits: 1.3.6.1.2.1.25.2.3.1.4.6`
这样就是物理内存大小及其已使用大小来求其使用率了。

3.使用存储信息里面的磁盘信息对磁盘的使用率进行监控，因为存储信息包含了虚拟内存和物理内存的使用率，所以会出现误报的情况，在设置阈值时，可以额外添加两条规则来避免这种情况：
`descr    不等于    Virtual Memory`
`descr    不等于    Physical Memory`

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
1. The problem mentioned in the title is solved, and the disk information can be found in the storage information.

2. Storage information includes not only disk information, but also memory information. One problem encountered during use is that the memory usage rate exceeds 100%. The reason is that the used size of virtual memory is divided by the size of physical memory. Modify the memory-related oid in src/main/resources/define/app-windows.yml to:
`hrMemorySize: 1.3.6.1.2.1.25.2.2.0`
 `hrStorageUsed: 1.3.6.1.2.1.25.2.3.1.6.6`
 `hrStorageAllocationUnits: 1.3.6.1.2.1.25.2.3.1.4.6`
This is the physical memory size and its used size to find its usage.

3. Use the disk information in the storage information to monitor the disk usage. Because the storage information includes the usage of virtual memory and physical memory, there will be false positives. When setting the threshold, you can add two additional rules to avoid this:
`descr is not equal to Virtual Memory`
`descr is not equal to Physical Memory`

**Comment by tomsun28** [comment]
@lfandrh 👍👍 很强，欢迎大佬把刚刚那个改动贡献一波到github仓库呀 https://github.com/dromara/hertzbeat/blob/collector-dashboard/manager/src/main/resources/define/app-windows.yml

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@lfandrh 👍👍 Very strong, welcome to contribute the change just now to the github warehouse https://github.com/dromara/hertzbeat/blob/collector-dashboard/manager/src/main/resources/define/app -windows.yml
