### ISSUE TITLE
[Task] [Suggest] Support the addition of one-click execution function without dependency environment

### ISSUE THREAD

**Issue by Suremotoo** [dromara/hertzbeat#1172]
## 建议功能：
为 hertzbeat 添加一个功能，使其能够脱离依赖环境，支持在不需要额外监控服务器的情况下，一键执行监控配置。

## 背景：
在一些情况下，没有额外的监控服务器可供使用，或者部署监控服务器不切实际。为了满足这些场景的需求，希望 hertzbeat 可以提供一种方式，使其可以在不依赖复杂环境的情况下运行。

## 预期实现：
开发一个**命令行工具**，用户可以将 hertzbeat 配置和测试的数据按照规范整理起来，用该命令行工具执行。
用户可以将这个命令行工具部署到运维机器，甚至是 U 盘等存储设备中。
用户执行命令行工具时，工具会根据配置自动执行相应的监控测试，并将结果报告生成为 HTML 或 PDF 格式，参考 #1171 。
通过这个功能，用户可以更灵活地执行监控配置，无需担心复杂的依赖环境。

## 思考
这个和 hertzbeat 的 docker 运行环境大体相似，但是并不完全相同，毕竟不能随便装 docker 到处跑，但是恰恰是命令行工具，重点是执行监控的测试结果，所以很多可视化的东西以及这些依赖的东西都不需要。

此条反馈与 #1171  整体是 1 个功能衍生出来的，但是从功能角度各有不同，故分开反馈。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

## Suggested features:
Add a function to hertzbeat so that it can break away from the dependent environment and support one-click monitoring configuration without the need for an additional monitoring server.

## background:
In some cases, no additional monitoring server is available, or it is impractical to deploy a monitoring server. In order to meet the needs of these scenarios, it is hoped that hertzbeat can provide a way to run without relying on a complex environment.

## Expected implementation:
Develop a **command line tool**, users can organize hertzbeat configuration and test data according to the specification, and use this command line tool to execute.
Users can deploy this command-line tool to operation and maintenance machines, or even storage devices such as U disks.
When the user executes the command-line tool, the tool will automatically execute the corresponding monitoring test according to the configuration, and generate the result report in HTML or PDF format, refer to #1171.
With this function, users can perform monitoring configuration more flexibly without worrying about complex dependency environments.

## think
This is roughly similar to hertzbeat's docker operating environment, but it is not exactly the same. After all, you can't just install docker to run around, but it is just a command line tool. The focus is on the test results of execution monitoring, so many visual things and these dependent things are unnecessary.

This feedback and #1171 are derived from one function as a whole, but they are different from the function point of view, so they are reported separately.


### Task List

_No response_

**Comment by tomsun28** [comment]
感觉老哥你说的功能有点像一键巡检，脱离监控系统独立执行一个巡检小工具来做到对当前主机资源的监测然后生成巡检报告。
这个小工具可能是我们想做的方向不一样，且和hertzbeat本身脱离了没有关系，感觉适合新开一个项目来做，但我们目前不会有这样的考虑，抱歉。可以找一下现有应该有类似的监控脚本命令行工具。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I feel that the function you mentioned is a bit like one-click inspection, which independently executes an inspection tool independently of the monitoring system to monitor the current host resources and then generate an inspection report.
This small tool may be in a different direction than what we want to do, and it has nothing to do with hertzbeat itself. It feels suitable for a new project, but we will not have such considerations at the moment, sorry. You can look for existing command line tools that should have similar monitoring scripts.

**Comment by Suremotoo** [comment]
这么说方向确实有点不一致，我想得简单了，我的想法是监控嘛，除了有定时任务的监控处理，也可以手动去检测，这也就有点像 一件巡检的意思，这也是我突发奇想，提出这个的原因。另一个就是基于 手动检测的前提，我都手动处理了，想看看本次执行的所有结果，也就对应到报告这个点上了。

虽然细细思考确实有点方向不同，不过还是感谢有这样的项目。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
In this way, the direction is indeed a bit inconsistent. I think it is simple. My idea is to monitor. In addition to the monitoring and processing of scheduled tasks, it can also be detected manually. This is a bit like a patrol inspection. On a whim, come up with the reason for this. The other is based on the premise of manual detection. I have manually processed it. I want to see all the results of this execution, which corresponds to the point of reporting.

Although it is indeed a bit different to think about it carefully, I am still grateful for such a project.
