### ISSUE TITLE
[Question] <title>Alarm convergence function abnormality

### ISSUE THREAD

**Issue by tengfei-wu** [dromara/hertzbeat#1277]
### Question

我设置告警收敛时间3分钟，测试“端口告警可用性”时，我下掉端口服务触发阈值并收到告警信息，间隔几秒，我上线端口服务此时收到告警恢复信息。间隔几秒，当我再次下掉端口服务时，没有收到告警信息。
发现如下几个问题：
（1）我看了下“告警中心”，没有最后一次下掉服务的告警记录。
（2）“端口可用性”栏目中，已经下掉的服务监控状态仍然是“正常监控”，但是打开该项监控图表，自下掉服务那段时间并没有数据。
（3）当我再上线该服务，图标数据正常生成，但是也没有收到恢复信息，告警中心也没有记录。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

I set the alarm convergence time to 3 minutes. When testing "port alarm availability", I lowered the trigger threshold of the port service and received an alarm message. After a few seconds, I brought the port service online and received the alarm recovery message. After a few seconds, when I disconnected the port service again, I did not receive an alarm message.
The following issues were found:
(1) I checked the "Alarm Center" and there is no alarm record of the last time the service was disconnected.
(2) In the "Port Availability" column, the monitoring status of the service that has been removed is still "Normal Monitoring", but when you open the monitoring chart, there is no data since the service was removed.
(3) When I went online with the service, the icon data was generated normally, but no recovery information was received, and there was no record in the alarm center.
