### ISSUE TITLE
[BUG] The app-jvm code_cache collect failed

### ISSUE THREAD

**Issue by Ceilzcx** [dromara/hertzbeat#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/48920254/196077545-fb5bdc59-9256-4592-83ac-1ca6c9acf915.png)

### Expected Behavior

expected： the code_cache show success

### Environment

```markdown
HertzBeat version(v2.0)
```

### Debug logs

![image](https://user-images.githubusercontent.com/48920254/196079083-54a69282-3ecb-47a7-aa9f-c76eca037692.png)

**Comment by tomsun28** [comment]
JMX Metrics: java.lang:type=MemoryPool,name=Code Cache In JRE8 BUT NOT JRE11.
In JRE11, CodeHeap 'non-nmethods' and CodeHeap 'non-profiled nmethods' instead of it. 
 
JRE8:

<img width="281" alt="2022-10-23 21 49 51" src="https://user-images.githubusercontent.com/24788200/197396163-c092eb63-4616-4b19-bd4a-f736e56e9339.png">

JRE11:

<img width="385" alt="2022-10-23 21 51 11" src="https://user-images.githubusercontent.com/24788200/197396186-201c5ed9-a35d-4d40-82d4-4d87948b9a3c.png">

It's very hard to compatible with both versions.   
Suggest we add attention document in hertzbeat doc to note that the `Code Cache` only support jre8 OR remove this metrics in jvm monitor.

**Comment by Ceilzcx** [comment]
我觉得还是继续保留吧，毕竟Java8用的人仍然很多，文档说明一下就行了
如果后续打算升级到Java11的可以考虑去掉
当然最好是可以通过Java版本控制是否展示code_cache，不过会影响现有的逻辑，感觉不是很好

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I think it's better to keep it. After all, there are still many people using Java8. The documentation will explain it.
If you plan to upgrade to Java 11 in the future, you can consider removing it
Of course, it is best to display code_cache through Java version control, but it will affect the existing logic, which is not very good

**Comment by tomsun28** [comment]
好的 那我们就先文档说明 我后面去弄下

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Okay, then let's document it first and I'll get it down later.
