### ISSUE TITLE
[Question] <java 内存溢出？占用过高虚拟内存经常10g以上>

### ISSUE THREAD

**Issue by fiendhous** [dromara/hertzbeat#371]
### Question

![her](https://user-images.githubusercontent.com/116266425/196910928-59216388-3d6e-4097-8a50-5cba20cc70a4.png)
![3h](https://user-images.githubusercontent.com/116266425/196910944-284d329b-09cc-4c5c-be53-cb277ed1879a.png)
![h1](https://user-images.githubusercontent.com/116266425/196910945-871d07a3-d5ab-4802-8afc-70ec953240f5.png)
![2h](https://user-images.githubusercontent.com/116266425/196910947-2018c82f-6d00-42a5-8c70-fad0595224a9.png)
[logs.zip](https://github.com/dromara/hertzbeat/files/9828361/logs.zip)

环境是herzbeat1.2.0   java11   mysql8.0.3   TDengine2.4.0.4   ubuntu-22.04.1-live-server-amd64安装包部署

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                  
  55406 root      20   0   11.2g   1.0g  27940 S   5.0  27.6   4:19.94 java                                                                                                                                                                     
  19071 root      20   0 2462700  66968   4716 S   1.0   1.7   1:42.86 taosadapter                                                                                                                                                              
    952 root      20   0 3737460 106772   6112 S   0.3   2.7  10:32.60 taosd                                                                                                                                                                    
  17050 mysql     20   0 3608860 425356  35336 S   0.3  10.7   5:46.68 mysqld

**Comment by tomsun28** [comment]
This due to the windows monitor use snmp protocol, the snmp service create too many thread but not reused, cause oom.

<img width="1263" alt="2022-10-23 20 02 52" src="https://user-images.githubusercontent.com/24788200/197391361-64c40d63-6b67-4b94-aaf0-e1c914f4cc98.png">

Fix by pr https://github.com/dromara/hertzbeat/pull/383 

After reused snmp thread. 


<img width="1274" alt="2022-10-23 20 13 56" src="https://user-images.githubusercontent.com/24788200/197391464-2ba3d2b7-5cf2-4273-b8ad-b1bc06bb3e20.png">

**Comment by tomsun28** [comment]
hi thanks for feedback, this issue has fixed by version v1.2.1
