### ISSUE TITLE
[BUG] <title> Monitoring status acquisition error

### ISSUE THREAD

**Issue by love19791126** [dromara/hertzbeat#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

虚拟机网络出现问题 导致机器的IP发生变化， 我在web-ui的监控里面修改了对应的设置 但是那个监控状态按钮显示的对应内容 就在正常监控和不可用之间来回的切换。

### Expected Behavior

虚拟机网络出现问题 导致机器的IP发生变化， 我在web-ui的监控里面修改了对应的设置 但是那个监控状态按钮显示的对应内容 就在正常监控和不可用之间来回的切换。

### Steps To Reproduce

虚拟机网络出现问题 导致机器的IP发生变化， 我在web-ui的监控里面修改了对应的设置 但是那个监控状态按钮显示的对应内容 就在正常监控和不可用之间来回的切换。

### Environment

```markdown
1.3.5
```

### Debug logs

虚拟机网络出现问题 导致机器的IP发生变化， 我在web-ui的监控里面修改了对应的设置 但是那个监控状态按钮显示的对应内容 就在正常监控和不可用之间来回的切换。

### Anything else?

虚拟机网络出现问题 导致机器的IP发生变化， 我在web-ui的监控里面修改了对应的设置 但是那个监控状态按钮显示的对应内容 就在正常监控和不可用之间来回的切换。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a problem with the virtual machine network, which causes the IP of the machine to change. I modified the corresponding settings in the web-ui monitoring, but the corresponding content displayed by the monitoring status button switches back and forth between normal monitoring and unavailable.

### Expected Behavior

There is a problem with the virtual machine network, which causes the IP of the machine to change. I modified the corresponding settings in the web-ui monitoring, but the corresponding content displayed by the monitoring status button switches back and forth between normal monitoring and unavailable.

### Steps To Reproduce

There is a problem with the virtual machine network, which causes the IP of the machine to change. I modified the corresponding settings in the web-ui monitoring, but the corresponding content displayed by the monitoring status button switches back and forth between normal monitoring and unavailable.

### Environment

```markdown
1.3.5
```


### Debug logs

There is a problem with the virtual machine network, which causes the IP of the machine to change. I modified the corresponding settings in the web-ui monitoring, but the corresponding content displayed by the monitoring status button switches back and forth between normal monitoring and unavailable.

### Anything else?

There is a problem with the virtual machine network, which causes the IP of the machine to change. I modified the corresponding settings in the web-ui monitoring, but the corresponding content displayed by the monitoring status button switches back and forth between normal monitoring and unavailable.

**Comment by tomsun28** [comment]
@love19791126 你好 你用的版本是1.2.5吗，这个问题可以重启解决，或者更新到最新版本1.3.0

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@love19791126 Hello, are you using version 1.2.5? This problem can be solved by restarting or updating to the latest version 1.3.0
