### ISSUE TITLE
[Task] It is hoped that the [Monitoring List] and [Alarm Center] pages can be added to filter devices based on tags

### ISSUE THREAD

**Issue by gaows20** [dromara/hertzbeat#776]
### Description

![image](https://user-images.githubusercontent.com/2405087/227826294-abf89a9a-b66c-40ee-ad63-8a6eaa5c274d.png)
![image](https://user-images.githubusercontent.com/2405087/227826382-182bb4dc-cc5b-4576-a9f3-89329a6e4186.png)

希望【监控列表】和【告警中心】页面可以增加 根据标签进行设备筛选，设备多了之后以便于管理。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description


![image](https://user-images.githubusercontent.com/2405087/227826294-abf89a9a-b66c-40ee-ad63-8a6eaa5c274d.png)
![image](https://user-images.githubusercontent.com/2405087/227826382-182bb4dc-cc5b-4576-a9f3-89329a6e4186.png)

It is hoped that the [Monitoring List] and [Alarm Center] pages can be added to filter devices based on tags, so that it will be easier to manage when there are more devices.

### Task List

_No response_

**Comment by tomsun28** [comment]
👍👍 Got it!

**Comment by vinci-897** [comment]
done
